# Site settings
title: Thiago Borges
description: "iOS, python, ruby and another things"
baseurl: ""
url: http://thiagoborg.es
twitter_username: tgabrielborges
github_username:  thiagogabriel

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jemoji
