- title: Cadeira Presidente Airys com Regulagens Avançadas
  url: http://pr.olx.com.br/regiao-de-londrina/moveis/cadeira-de-escritorio-profissional-ultra-confortavel-459770747
  image: cadeira-presidente-airys.jpg

- title: Abridor de vinhos elétrico
  url: http://pr.olx.com.br/regiao-de-londrina/utilidades-domesticas/abridor-de-vinhos-eletrico-457044870
  image: abridor-de-vinho.jpg
