- title: Cafeteira French Press 1L com filtro duplo
  url: http://pr.olx.com.br/regiao-de-londrina/utilidades-domesticas/cafeteira-french-press-1-l-com-filtro-duplo-460760305
  image: cafeteira-french-press.jpg

- title: Cadeira Presidente Airys com Regulagens Avançadas
  url: http://pr.olx.com.br/regiao-de-londrina/moveis/cadeira-de-escritorio-profissional-ultra-confortavel-459770747
  image: cadeira-presidente-airys.jpg

- title: Abridor de vinhos elétrico
  url: http://pr.olx.com.br/regiao-de-londrina/utilidades-domesticas/abridor-de-vinhos-eletrico-457044870
  image: abridor-de-vinho.jpg

- title: Mochila para notebook Chenson
  url: http://pr.olx.com.br/regiao-de-londrina/computadores-e-acessorios/mochila-para-notebook-chenson-usada-459782644
  image: mochila-notebook.jpg
